branch-defaults:
  master:
    environment: Yukstay-www
environment-defaults:
  Yukstay-www:
    branch: null
    repository: null
global:
  application_name: YukStay
  default_ec2_keyname: production-n-virginia
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Node.js running on
    64bit Amazon Linux/4.5.1
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: yukstay
  sc: git
  workspace_type: Application
